name = "kota-db-site-web-staging"
compatibility_date = "2025-02-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Runtime-specific environment variables should be managed through Cloudflare Pages
# project settings to avoid overriding dashboard configuration during deploys.
