name = "kotadb-app"
compatibility_date = "2025-02-10"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Compatibility settings and environment variables should be managed via
# Cloudflare Pages configuration to keep deploys aligned with the dashboard.
