name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
      - "feature/**"
      - "fix/**"

jobs:
  deploy-preview:
    name: Deploy Preview to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint (web)
        working-directory: ./apps/web
        run: pnpm run lint

      - name: Typecheck (web)
        working-directory: ./apps/web
        run: pnpm run typecheck

      - name: Build marketing site (preview)
        working-directory: ./apps/web
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          NEXT_PUBLIC_STRIPE_SOLO_PRICE_ID: ${{ secrets.NEXT_PUBLIC_STRIPE_SOLO_PRICE_ID }}
          NEXT_PUBLIC_STRIPE_TEAM_PRICE_ID: ${{ secrets.NEXT_PUBLIC_STRIPE_TEAM_PRICE_ID }}
          NEXT_PUBLIC_APP_URL: https://preview.kotadb.io
          NEXT_PUBLIC_DASHBOARD_URL: https://preview-app.kotadb.io
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          pnpm run build
          pnpm run build:cf

      - name: Compute preview branch name
        id: preview
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "name=preview-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "name=preview-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Ensure Pages project exists (web)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx -y wrangler@4 pages project create kotadb-web --production-branch=main --no-git >/dev/null 2>&1 || echo "Project kotadb-web exists or creation skipped"

      - name: Deploy Preview via Wrangler
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx -y wrangler@4 pages deploy ./apps/web/.vercel/output/static \
            --project-name=kotadb-web \
            --branch=${{ steps.preview.outputs.name }}

      - name: Add preview URL comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const branch = `preview-${context.issue.number}`;
            const url = `https://${branch}.kotadb-web.pages.dev`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment ready!\n\n🔗 [View Preview](${url})`
            });
